#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PRODUCT = ROOT / "products" / "chummer"


REQUIRED_MARKERS: dict[str, tuple[str, ...]] = {
    "FLAGSHIP_PUBLIC_FRONT_REDESIGN.md": (
        "minimalist and human-authored",
        "Primary actions: `Stable`, `Nightly`, `Help`",
        "no visible machinery, provider labels, proof jargon, or assistant provenance",
        "Black Ledger is not a primary homepage gateway",
    ),
    "PUBLIC_LANDING_POLICY.md": (
        "public product homepage, download front door, and help entry",
        "Proof and verification language belongs behind status, progress, or advanced trust routes",
        "The landing page must show what is real now without asking the visitor to read the release machinery.",
    ),
    "PUBLIC_DOWNLOADS_POLICY.md": (
        "The downloads surface is a download shelf first",
        "show visible `Nightly` and `Stable` lane buttons",
        "expose portable builds on the normal public shelf",
        "keep advanced release records away from the normal install choice",
        "when an Arch/AUR package is available or still pending",
    ),
    "PUBLIC_RELEASE_EXPERIENCE.yaml": (
        "Claim your copy",
        "publishes at most one scheduled morning public shelf update per day",
        "Arch-based distributions should receive an AUR package projection",
    ),
    "RELEASE_PIPELINE.md": (
        "## Scheduled rolling release rule",
        "normal publication happens once per day at 08:00 Europe/Vienna",
        "## Arch/AUR package rule",
        "emergency publishes require an explicit release reason",
    ),
    "DESKTOP_CLIENT_PRODUCT_CUT.md": (
        "no public portable CTA",
        "attribute editing uses compact `-` / `+` steppers",
        "text-entry surfaces use the shell theme",
        "AUR target next",
    ),
    "DESKTOP_VISUAL_FAMILIARITY_EXIT_GATE.md": (
        "compact `-` / `+` steppers",
        "every text-entry surface uses the shell text-input theme",
        "any textbox shows duplicate overlapping hover text",
    ),
    "SURFACE_DESIGN_SYSTEM_AND_AI_REVIEW_LOOP.md": (
        "provide one global `Assisted features` setting",
        "hide the related buttons and behavior",
        "insulting or shaming language",
        "`Claim your copy` as the user-facing relationship action",
    ),
    "ACCOUNT_AWARE_INSTALL_AND_SUPPORT_LINKING.md": (
        "online `Claim your copy` flow",
        "Normal UI must not expose a manual activation ritual",
        "fallback is a clear online claim link or support repair path",
    ),
}

FORBIDDEN_PUBLIC_FRONT_MARKERS = (
    "product homepage, proof shelf",
    "generated by AI",
    "login via webpage",
    "manual activation",
    "every successful mainline Windows `win-x64` and Linux `linux-x64` build is a release",
)


def main() -> int:
    errors: list[str] = []

    for relative_path, markers in REQUIRED_MARKERS.items():
        path = PRODUCT / relative_path
        if not path.is_file():
            errors.append(f"missing_file:{relative_path}")
            continue

        text = path.read_text(encoding="utf-8")
        for marker in markers:
            if marker not in text:
                errors.append(f"missing_marker:{relative_path}:{marker}")

    public_text = "\n".join(
        (PRODUCT / relative_path).read_text(encoding="utf-8")
        for relative_path in (
            "FLAGSHIP_PUBLIC_FRONT_REDESIGN.md",
            "PUBLIC_LANDING_POLICY.md",
            "PUBLIC_DOWNLOADS_POLICY.md",
            "PUBLIC_RELEASE_EXPERIENCE.yaml",
            "RELEASE_PIPELINE.md",
        )
        if (PRODUCT / relative_path).is_file()
    )
    for marker in FORBIDDEN_PUBLIC_FRONT_MARKERS:
        if marker in public_text:
            errors.append(f"forbidden_marker:{marker}")

    if errors:
        for error in errors:
            print(error)
        return 1

    print("MINIMAL_PUBLIC_SURFACE_DESIGN_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
